!!python/object:__main__.Configuration
repositoryUrl: 'https://github.com/dotnet/templates'
repositoryShortname: 'dotnet/templates'
repositoryPath: 'C:\Repos\dotnet.templates'
batchSizeInMonths: 99
analysisOutputPath: 'C:\Repos\analysisOutput'
aliasPath: 'C:\Repos\analysisOutput\aliases\dotnet.templates.yml'
aliasSimilarityMaxDistance: 0.75
sentiStrengthJarPath: 'C:/SentStrength/SentiStrength.jar'
sentiStrengthDataPath: 'C:/SentStrength/SentiStrength_Data/'